---
# This role creates the AWS ELB and configures it.
- name: Create the ELB in AWS
  ec2_elb_lb:
    name: "jl-windows-demo-lb"
    state: present
    region: us-east-2
    zones:
      - us-east-2a
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
